version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/lab_man1/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data_lab:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lab_man
      - POSTGRES_PASSWORD=lab_man
      - POSTGRES_DB=lab_man_dev

volumes:
  postgres_data_lab:
