# Generated by Django 2.2 on 2020-12-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlalgorithm',
            name='joblib_binary_file',
        ),
        migrations.AddField(
            model_name='mlalgorithm',
            name='joblib_binary_file_algorithm',
            field=models.BinaryField(blank=True, default=None, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='mlalgorithm',
            name='joblib_binary_file_encoders',
            field=models.BinaryField(blank=True, default=None, editable=True, null=True),
        ),
    ]
