# Generated by Django 2.2 on 2020-12-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_auto_20201205_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlrequest',
            name='feedback',
        ),
    ]
